# Generated by Django 4.2.7 on 2023-11-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='similaridade',
            name='categoria',
            field=models.CharField(choices=[('SYNTHETIC', 'Synthetic'), ('NATURAL', 'Natural'), ('DRUG', 'Drug')], default='', max_length=100),
        ),
    ]
