# Generated by Django 4.2.7 on 2023-11-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_similaridade_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoSDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sdf', models.FileField(upload_to='arquivos_sdf/')),
            ],
        ),
    ]
