# Generated by Django 4.2.7 on 2023-11-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_arquivosdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similaridade',
            name='sdf',
            field=models.FileField(upload_to=''),
        ),
    ]
