# Generated by Django 4.2.7 on 2023-12-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_remove_similaridade_nome_alter_similaridade_sdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='similaridade',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
