# Generated by Django 4.2.7 on 2023-12-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0009_similaridade_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='similaridade',
            name='img',
            field=models.CharField(blank='False', max_length=100),
        ),
    ]
