# Generated by Django 4.2.7 on 2023-12-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0010_similaridade_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='similaridade',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
