# Generated by Django 4.2.7 on 2023-12-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0012_similaridade_data_mol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similaridade',
            name='img',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d'),
        ),
    ]
