# Generated by Django 4.2.7 on 2023-12-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0013_alter_similaridade_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similaridade',
            name='img',
            field=models.CharField(blank='False', max_length=100),
        ),
    ]
