# Generated by Django 4.2.7 on 2024-03-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0015_alter_similaridade_sdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similaridade',
            name='img',
        ),
        migrations.AddField(
            model_name='similaridade',
            name='observacoes_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Observações do Administrador'),
        ),
    ]
