# Generated by Django 4.2.7 on 2024-03-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0016_remove_similaridade_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similaridade',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
