# Generated by Django 4.2.7 on 2024-03-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0017_alter_similaridade_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similaridade',
            name='smile',
            field=models.CharField(max_length=300),
        ),
    ]
