# Generated by Django 4.2.7 on 2025-08-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0018_alter_similaridade_smile'),
    ]

    operations = [
        migrations.AddField(
            model_name='similaridade',
            name='fingerprint',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
