# Generated by Django 4.2.24 on 2025-10-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0019_similaridade_fingerprint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='similaridade',
            old_name='fingerprint',
            new_name='pharm_fingerprint',
        ),
    ]
